import numpy as np
int_arr=np.array([1,2,3])
print(int_arr)
print(int_arr.dtype)
float_arr=np.array([1.4,5.6,4.7])
print(float_arr)
print(float_arr.dtype)
bool_arr=int_arr>=2
print(bool_arr)
print(bool_arr.dtype)
print(np.where(bool_arr))
#返回的是元组，第一位是一个true位置的数组，类型是int64

mixed_arr=np.array([1.3,3,4])
print(mixed_arr.dtype)
#如果后期进行改变，会进行截断，维护集体，除非重新赋值
int_arr[2]=3.14
print(int_arr)
print(int_arr.dtype)
#被集体同化
float_arr=np.array([1.2,3.0,4.0])
float_arr[2]=3
print(float_arr)
print(float_arr.dtype)
#共同改变定理,astype目标的类型
int_arr=float_arr.astype(int)
print(int_arr)
print(int_arr.dtype)

arr2=np.array([[1,2],[3,4]])
print(arr2)
print(arr2.dtype)
#左闭右开的生成递增数组
arr_arrange=np.arange(0,10,2)
print(arr_arrange)
#左闭右闭的生成确定数目的数组
arr_lin=np.linspace(0,1,7)
print(arr_lin)
#创建同值数组
arr_0=np.zeros((2,3))
print(arr_0)
arr_1=np.ones((3,4))
print(arr_1)
arr_num=np.full((3,4),5)
print(arr_num)
#未初始化的数组
empty_arr=np.empty((1,3),dtype=int)
print(empty_arr)
#生成随机数组,01区间均匀分布
rand_arr=np.random.rand(2,2)
print(rand_arr)
#随机数组，01正态分布
randn_arr=np.random.randn(2,2)
print(randn_arr)
#生成指定范围内的随机整数数组
randint_arr=np.random.randint(1,10,(2,3))
print(randint_arr)
#随机种子seed
np.random.seed(134)
seed_arr=np.random.rand(2,2)
print(seed_arr)
seed_arr=np.random.rand(2,2)
print(seed_arr)
seed_arr=np.random.rand(2,2)
print(seed_arr)

#基础访问
arr=np.array([[1,2,3],[5,6,7]])
print(arr[0,1])
print(arr[-1])
#花式索引
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
d=[1,2]
f=[0,1]
#这种是一一对应的，最后只有两个
print('花式索引',arr[[d],[f]])
print('花式索引',arr[[1,2],[0,1]])

#切片索引
arr=np.array([1,2,3,4,5])
print('arr',arr)
print('arr[1:3]',arr[1:3])

arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr[:2,1:])
#数组切片返回的视图，改变切片改变数组，可以用copy实现只改切片不该原数组
#等号直接赋值是绑定，是引用，会最直接改，不改原数据就需要copy

arr=np.array([[1,2],[3,4]])
print(arr)
print(arr.T)
print(arr.transpose())
#翻转：切片和flip两种，axis应该是描述维度的一个参数
arr=[1,2,3,4,5]
print(arr)
print(arr[::-1])
print('垂直翻转',np.flip(arr,axis=0))
print('水平翻转',np.flip(arr))
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr)
print(arr[::-1])
print('垂直翻转',np.flip(arr,axis=0))
print('水平翻转',np.flip(arr,axis=1))

arr=np.arange(6)
reshaped=arr.reshape(2,3)
print(arr)
print(reshaped)
#占位符重塑
arr=np.arange(12)
reshaped=arr.reshape(3,-1)
print(reshaped)
reshaped=arr.reshape(-1,4)
print(reshaped)
#若个数不对应会抛出valueerror
#聚合部分跳了一下
a=np.array([1,2])
b=np.array([3,4])
print(np.vstack((a,b)))
a=np.array([[1],[2],[3]])
b=np.array([[4],[5],[6]])
print(np.hstack((a,b)))
#数组分裂部分的实践有跳跃
arr=np.arange(9)
split_arr=np.split(arr,3)
for i,sub_arr in enumerate(split_arr):
    print(i+1,sub_arr)
#数组的标量计算跳了
a=np.array([1,2,3])
b=np.array([4,5,6])
print(a+b)
print(a-b)
#广播部分好像明白了